Release 0.4.0
redBorder/cookbook-rb-ips pull request #37
Opened 2024-06-21 08:13 UTC by jsotofernandez

@davidredborder 
    - [2bdb85f] fix lint
    - [0c5d6f6] add exporter service to ips

2024-06-21 12:51 UTC, JPeraltaNic commented on CHANGELOG.md
> +    - [2bdb85f] fix lint
```suggestion
    - [2bdb85f] fix lint
```
This line could be ommited; it's not necessary to indicate fixes in lint inside the changelog

2024-06-26 08:01 UTC, ljblancoredborder requested changes

2024-06-26 08:01 UTC, ljblancoredborder commented on resources/recipes/configure.rb
> +rb_exporter_config 'Configure rb-exporter' do
this is not following the ternary normalization

2024-06-26 08:17 UTC, JPeraltaNic approved these changes

2024-06-26 08:53 UTC, ljblancoredborder approved these changes

2024-06-26 08:53 UTC, merged